default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rest_api_development


test:
  <<: *default
  database: rest_api_test


production:
  <<: *default
  database: rest_api_production
  username: rest_api
  password: <%= ENV['REST_API_DATABASE_PASSWORD'] %>